# Generated by Django 3.2.2 on 2021-06-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210506_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='ammount',
            new_name='amount',
        ),
    ]
