# Generated by Django 3.2.2 on 2021-06-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_ammount_expenses_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomes',
            old_name='ammount',
            new_name='amount',
        ),
    ]
