# Generated by Django 3.2.2 on 2021-06-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='expense_category',
            new_name='kategoria',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='amount',
            new_name='kwota',
        ),
    ]
