# Generated by Django 3.2.2 on 2021-06-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210609_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomes',
            old_name='income_category',
            new_name='kategoria_przychodu',
        ),
        migrations.RenameField(
            model_name='incomes',
            old_name='amount',
            new_name='kwota',
        ),
    ]
