# Generated by Django 3.2.2 on 2021-06-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210609_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='kwota',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='kategoria',
            new_name='expense_category',
        ),
        migrations.RenameField(
            model_name='incomes',
            old_name='kwota',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='incomes',
            old_name='kategoria_przychodu',
            new_name='income_category',
        ),
    ]
