# Generated by Django 3.2.2 on 2021-06-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_incomes_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expenses',
            table='expenses',
        ),
    ]
